version: "2"
services:
  app:
    container_name: app
    restart: on-failure
    networks:
      - questdb
    build:
      context: .
    depends_on:
      - "questdb"
    command: ["./wait-for-it.sh"]
  questdb:
    container_name: questdb
    image: questdb/questdb
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
    networks:
      - "questdb"
    volumes:
      - ./data/db:/root/.questdb/db

networks:
  questdb:
